### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by sharkdp** [bingryan/json-tools#1]
Hi. I found your project by chance. It looks like you copied large parts of `bat`s source code into your project. Notably in:

- `json-tools/module/input/src/lib.rs` (https://github.com/bingryan/json-tools/blob/e3eaa8e7d4ccf6804ff8fcecd0b993736f959841/module/input/src/lib.rs) (Compare with: https://github.com/sharkdp/bat/blob/b489fc75c9e6f54ab0dd855351df4a33a109a493/src/input.rs)
- `json-tools/module/app/src/lib.rs` (https://github.com/bingryan/json-tools/blob/e3eaa8e7d4ccf6804ff8fcecd0b993736f959841/module/app/src/lib.rs)

I didn't look further.

I could not find any attribution, as required by our [LICENSE](https://github.com/sharkdp/bat/blob/b489fc75c9e6f54ab0dd855351df4a33a109a493/LICENSE-MIT#L8-L11). Could you please clarify?

**Comment by bingryan** [comment]
hey, @sharkdp ,Thank you for creating bat.  In my computer, I replaced cat with bat。 when I was planning to write this  project, I directly referred to the source code of bat for the logic of processing input files and text. because it is very well written, I copied it directly.  forgive me for doing this, because I didn’t do it for profit. what do you think i should do.

**Comment by sharkdp** [comment]
Hi @bingryan. No worries. But if you copy source code, you must adhere to the licensing terms. In this case, it's enough to copy `bat`s [LICENSE](https://github.com/sharkdp/bat/blob/b489fc75c9e6f54ab0dd855351df4a33a109a493/LICENSE-MIT) file into the respective source files (for example: as a comment at the top). Good luck with your project!

**Comment by bingryan** [comment]
hey, @sharkdp, 

- json-tools/module/input/src/lib.rs (https://github.com/bingryan/json-tools/blob/e3eaa8e7d4ccf6804ff8fcecd0b993736f959841/module/input/src/lib.rs) 
- json-tools/module/app/src/lib.rs (https://github.com/bingryan/json-tools/blob/e3eaa8e7d4ccf6804ff8fcecd0b993736f959841/module/app/src/lib.rs)

I added in the head of the file
